name: ${project.artifactId}
main: com.thevoxelbox.voxeltimer.VoxelTimer
version: ${project.build.version}
website: ${project.url}
authors: [Giltwist, MikeMatrix]
description: ${project.description}
commands:
  vtstart:
    description: Start a server event
    usage: |
           /<command> <EventName> <duration> [TPonjoin:default true]
           Example: /<command> - need to write the help.
  vtlist:
    description: List active server events and remaining time
    usage: |
           /<command>
           Example: /<command> - need to write the help.
  vtjoin:
    description: If enabled, allows player to be TPed to an event
    usage: |
           /<command> <EventName>
           Example: /<command> - need to write the help.
  vtstop:
    description: Stops a server event
    usage: |
           /<command> <EventName>
           Example: /<command> - need to write the help.
